### ISSUE TITLE
libbattlecode-linux.a is not compiled with optimization

### ISSUE THREAD

**Issue by simonlindholm** [battlecode/battlecode-2018#114]
Hard to make a PR for without more insight into the release processes, but the libbattlecode-linux.a I see in the scafford does not appear to be compiled with optimization, judging by the assembly. This probably slows the Rust code down by quite a large factor (I didn't measure yet).

**Comment by kazimuth** [comment]
Hm, in the current build process it's built with `--release`; you can run `make linux-libs copy-linux` in the root directory of the repo to watch the build process. (We build in an ubuntu docker image for linux because the release is orchestrated from a mac machine). I just ran a build and as far as I can tell it used the correct artifacts.

It's possible I screwed up during one of the past releases and used the debug build instead of the release build, or I'm missing something, though.

**Comment by kazimuth** [comment]
It's possible that we're accidentally doing something in the codebase that inhibits optimization, as well. There's definitely some low-hanging performance fruit in the engine.

**Comment by simonlindholm** [comment]
Oh, erm, sorry, I was looking at an old scaffold. Never mind this issue! The current one looks fine.
