### ISSUE TITLE
Better error handling in GameWorld::apply_turn

### ISSUE THREAD

**Issue by simonlindholm** [battlecode/battlecode-2018#127]
If the unwrap in GameWorld::apply_turn fails, either:

- a player sent invalid JSON back, circumventing the API. That action should either be ignored, or the player should lose.
- there was a synchronization bug, like what I imagine happened here: https://pastebin.com/wt3t3mdK (shared by [test bot please ignore] stuartj). It would be very nice to dump the JSON log to file in this case for debugging purposes, if that doesn't happen already.

**Comment by simonlindholm** [comment]
Several errors are popping up that look like the pastebin, and someone hinted that they might be related to running out of time (maybe the old message forging that broke things? I haven't a clue).

**Comment by kazimuth** [comment]
I'm pretty sure I addressed this problem with 0.11.1, there was an incorrect constant in the timing code (it allowed players to continue playing if their time pool got above the limit, which would break due to the API sending diffs). Hopefully that should be fixed now that players stop running forever once they run out of time.

If anyone runs into this on 0.11.1 or later, please comment here.

**Comment by simonlindholm** [comment]
Ok, I suspected that could be related. Could be worth an announcement in #known-fixes (also to hear whether someone has the problem with >=0.11.1).

**Comment by simonlindholm** [comment]
Fixed by #136.
